env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  import/prefer-default-export:
    - off
  no-await-in-loop:
    - off
  '@typescript-eslint/no-use-before-define':
    - off
  no-continue:
    - off
  class-methods-use-this:
    - off
  no-underscore-dangle:
    - off
root: true
